name: HyperWarp
version: 1.0.0
author: SciDev
api-version: 1.16
main: me.scidev.hyperwarp.HyperWarp
commands:
   setwarp:
      description: Define a new warp destination.
      permission: hyperwarp.commands.setwarp.use
      aliases: ["sw"]
      usage: "/<command> <warp name> [x] [y] [z] [pitch] [yaw] [world] [permissionNode] [description... ]"
   editwarp:
      description: Modify an existing warp.
      permission: hyperwarp.commands.editwarp.use
      aliases: ["ew"]
      usage: "\n - /<command> <warp name> rename <new name>\n - /<command> <warp name> location <x> <y> <z>\n - /<command> <warp name> rotation <pitch> <yaw>\n - /<command> <warp name> world <world>\n - /<command> <warp name> permission <permission>\n - /<command> <warp name> description <description>"
   delwarp:
      description: Remove an existing warp.
      permission: hyperwarp.commands.delwarp.use
      aliases: ["dw"]
      usage: "/<command> <warp name>"
   warp:
      description: Teleport to a warp.
      permission: hyperwarp.commands.warp.use
      aliases: ["w"]
      usage: "/<command> <warp name>"
   getwarp:
      description: Get information about a warp.
      permission: hyperwarp.commands.getwarp.use
      aliases: ["warpinfo","wi","gw"]
      usage: "/<command> <warp name>"
   listwarps:
      description: Remove an existing warp.
      permission: hyperwarp.commands.listwarps.use
      aliases: ["warps","lw"]
      usage: "/<command>"
permissions:
   hyperwarp.commands.listwarps.use:
      default: true
   hyperwarp.commands.warp.use:
      default: true
   hyperwarp.commands.getwarp.use:
      default: true
   hyperwarp.commands.setwarp.use:
      default: op
   hyperwarp.commands.editwarp.use:
      default: op
   hyperwarp.commands.delwarp.use:
      default: op
